#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RideWithMe.Resource", IsApplication=true)]

namespace RideWithMe
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::RideWithMe.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::RideWithMe.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int rmwicon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int rwm_bg = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int Text_listfromDB = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int btn_admin = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int btn_driver = 2131034120;
			
			// aapt resource value: 0x7f050021
			public const int btn_next = 2131034145;
			
			// aapt resource value: 0x7f05001b
			public const int btn_reg = 2131034139;
			
			// aapt resource value: 0x7f05000b
			public const int btn_regme = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int btn_rider = 2131034119;
			
			// aapt resource value: 0x7f05002c
			public const int btn_sendriderRequest = 2131034156;
			
			// aapt resource value: 0x7f05001e
			public const int cb_driver = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int cb_rider = 2131034141;
			
			// aapt resource value: 0x7f05002b
			public const int input_dropoff = 2131034155;
			
			// aapt resource value: 0x7f050003
			public const int input_email = 2131034115;
			
			// aapt resource value: 0x7f050014
			public const int input_emailreg = 2131034132;
			
			// aapt resource value: 0x7f05000e
			public const int input_fname = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int input_lname = 2131034128;
			
			// aapt resource value: 0x7f050016
			public const int input_passreg = 2131034134;
			
			// aapt resource value: 0x7f050005
			public const int input_passwd = 2131034117;
			
			// aapt resource value: 0x7f050012
			public const int input_phone = 2131034130;
			
			// aapt resource value: 0x7f050029
			public const int input_pickup = 2131034153;
			
			// aapt resource value: 0x7f05001a
			public const int input_plate = 2131034138;
			
			// aapt resource value: 0x7f050025
			public const int input_riderDate = 2131034149;
			
			// aapt resource value: 0x7f050027
			public const int input_riderTime = 2131034151;
			
			// aapt resource value: 0x7f050018
			public const int input_vtype = 2131034136;
			
			// aapt resource value: 0x7f050024
			public const int label_date = 2131034148;
			
			// aapt resource value: 0x7f05002a
			public const int label_droppoff = 2131034154;
			
			// aapt resource value: 0x7f050002
			public const int label_email = 2131034114;
			
			// aapt resource value: 0x7f050013
			public const int label_emailreg = 2131034131;
			
			// aapt resource value: 0x7f05000d
			public const int label_fname = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int label_lname = 2131034127;
			
			// aapt resource value: 0x7f050006
			public const int label_login = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int label_notreg = 2131034122;
			
			// aapt resource value: 0x7f050015
			public const int label_passreg = 2131034133;
			
			// aapt resource value: 0x7f050004
			public const int label_passwd = 2131034116;
			
			// aapt resource value: 0x7f050011
			public const int label_phone = 2131034129;
			
			// aapt resource value: 0x7f050028
			public const int label_pickup = 2131034152;
			
			// aapt resource value: 0x7f050019
			public const int label_plate = 2131034137;
			
			// aapt resource value: 0x7f050023
			public const int label_pls = 2131034147;
			
			// aapt resource value: 0x7f050026
			public const int label_time = 2131034150;
			
			// aapt resource value: 0x7f05000c
			public const int label_userreg = 2131034124;
			
			// aapt resource value: 0x7f050017
			public const int label_vtype = 2131034135;
			
			// aapt resource value: 0x7f050022
			public const int label_welcrider = 2131034146;
			
			// aapt resource value: 0x7f050000
			public const int label_weldriver = 2131034112;
			
			// aapt resource value: 0x7f05001c
			public const int textView1 = 2131034140;
			
			// aapt resource value: 0x7f05001f
			public const int textView2 = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int textView3 = 2131034144;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Admin = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Driver = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int RegistrationDriver = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RegistrationRider = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int RegOptions = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Rider = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
