#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RideWithMe.Resource", IsApplication=true)]

namespace RideWithMe
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int rmwicon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int btn_admin = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int btn_driver = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int btn_reg = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int btn_rider = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int input_email = 2131034113;
			
			// aapt resource value: 0x7f050012
			public const int input_emailreg = 2131034130;
			
			// aapt resource value: 0x7f05000c
			public const int input_fname = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int input_lname = 2131034126;
			
			// aapt resource value: 0x7f050014
			public const int input_passreg = 2131034132;
			
			// aapt resource value: 0x7f050003
			public const int input_passwd = 2131034115;
			
			// aapt resource value: 0x7f050010
			public const int input_phone = 2131034128;
			
			// aapt resource value: 0x7f050018
			public const int input_plate = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int input_vtype = 2131034134;
			
			// aapt resource value: 0x7f050000
			public const int label_email = 2131034112;
			
			// aapt resource value: 0x7f050011
			public const int label_emailreg = 2131034129;
			
			// aapt resource value: 0x7f05000b
			public const int label_fname = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int label_lname = 2131034125;
			
			// aapt resource value: 0x7f050004
			public const int label_login = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int label_notreg = 2131034120;
			
			// aapt resource value: 0x7f050013
			public const int label_passreg = 2131034131;
			
			// aapt resource value: 0x7f050002
			public const int label_passwd = 2131034114;
			
			// aapt resource value: 0x7f05000f
			public const int label_phone = 2131034127;
			
			// aapt resource value: 0x7f050017
			public const int label_plate = 2131034135;
			
			// aapt resource value: 0x7f05000a
			public const int label_userreg = 2131034122;
			
			// aapt resource value: 0x7f050015
			public const int label_vtype = 2131034133;
			
			// aapt resource value: 0x7f050019
			public const int textView9 = 2131034137;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Register = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
